spring.application.name=primo-bot
server.port=8086

spring.main.banner-mode=off
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

management.endpoints.web.exposure.include=health
